version: '3.8'
services:
  server:
    image: node:lts-alpine
    ports:
      - '8080:80'
    volumes:
      - ./server:/root/server
    entrypoint: sh /root/server/start_server.sh
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./out:/var/www/html
      - ./default.conf:/etc/nginx/sites-available/default
    depends_on:
      - server
